### ISSUE TITLE
this is taking me a long time

### ISSUE THREAD

**Issue by XGilmar** [Awesomesh0t/awesomeshot#16]
My directory path is `/storage/picture/ScreenMaster` try that and the default `/sdcard/picture/ScreenMaster`. Nothing seems to get better, I don't know if I'm doing something wrong I use these commands
`cd awesomeshot;
 ls;
 nvim awesomeshot.conf;
`
try with the default one and also try changing the directory   `screenshot_result_path="/sdcard/Pictures/ScreenMaster"`  >> `/storage/picture/ScreenMaster`

`awesomeshot -a`

![IMG_20220822_003326](https://user-images.githubusercontent.com/86094668/185849437-2404017e-8ccf-4587-a337-44eb293ec378.jpg)

 `awesomeshot -m /data/data/com.termux/files/home/storage/pictures/ScreenMaster/fondo_20220822_002626.png`

![IMG_20220822_003531](https://user-images.githubusercontent.com/86094668/185849441-b9182139-820d-44ff-b4cf-3d6e5b82399c.jpg)

 It stays that way for a long time. `awesomeshot -a` gives me a directory error and `awesomeshot -m` saves me a backup but neither of the two methods generates the edited image.

**Comment by armandwipangestu** [comment]
## Question no. 1

When you try awesomeshot with argument `-a` or `--auto` and then you edit variable value `screenshot_result_path` is the config file you changed in the awesomeshot directory (from cloning this repository)? Ex: 

`/somewhere/foo/bar/awesomeshot/awesomeshot.conf`

If it yes it will be not working, because awesomeshot will be read or source the variable of configuration from `~/.config/awesomeshot/awesomeshot.conf`.

That's why the error output when script running to backup original photo, show the directory still default config (not changed)

Reference: [Awesomeshot - Config File Location](https://github.com/mayTermux/awesomeshot/wiki/Customizing-Config-File#config-file-location)

## Question no. 2

I have no idea why argument `-m` or `--manual` not working on you (but copy or backup work), it should be work because the user set PATH manually and directly to the file. Or maybe you can run with this PATH (i guess)

```bash
awesomeshot -m /sdcard/pictures/ScreenMaster/foobar.png
```

## Conclusion

 NOTE: This might not work because of the ImageMagick
>
> If you want to try if imagemagick is working oke, you can put the code from one of the functions from binary Awesomeshot and then run on your terminal, Ex Second Border function:
>
> ### Load config
>
> ```bash
> source ~/.config/awesomeshot/awesomeshot.conf
> ```
>
> ### Run ImageMagick to edit the image
>
> ```bash
> convert "/foo/bar/ex.png" -bordercolor "${second_border_color}" -border ${second_border_size} "/foo/bar/ex.png"
> ```
> 
> | Example |
> |--|
> |![Screenshot_20220822_215218](https://user-images.githubusercontent.com/64394320/185952425-1b6832ca-4101-4be7-9084-d4f76c565e66.png)|
>
> If you don't want the Second Border edited by variable or config file, you can read this: [Awesomeshot - Customizing Config File - Second Border](https://github.com/mayTermux/awesomeshot/wiki/Customizing-Config-File#second-border)
>
> ### Result
>
> |Before|After|
> |--|--|
> |![testing](https://user-images.githubusercontent.com/64394320/185952021-ad2d1bf4-1d0a-4f94-81ed-5c6ecb16dc74.png)|![Screenshot_20220822_214221](https://user-images.githubusercontent.com/64394320/185952135-3a882911-7f49-4958-9fdb-8086102f6377.png)|

**Comment by armandwipangestu** [comment]
FYI: On some versions awesomeshot (or maybe just v.1.1.3) there is a bug in the copy file section, sometimes it runs smoothly and sometimes it can't read a file

![Screenshot_20220822_221405](https://user-images.githubusercontent.com/64394320/185957284-c139a830-e52a-45b0-9a4a-053124c8400a.png)

Maybe it will be fix later, for now I'm a little busy with my work and college

**Comment by XGilmar** [comment]
Thanks for taking the time to reply, It seems that I can only modify my image with the `convert "/foo/bar/ex.png" -bordercolor "${second_border_color}" -border ${second_border_size} "/foo/bar/ex.png"` command. I would really like you to make a tutorial video, it doesn't need much editing. This is in order to resolve many doubts towards people.✌🏻

![fondo_20220822_182517](https://user-images.githubusercontent.com/86094668/186042364-4d8c5e17-5a41-4dfb-85e4-f084bee58882.png)


![fondo](https://user-images.githubusercontent.com/86094668/186042367-fe7d6728-eaef-4a58-a5d1-8af173ec5b63.png)
