### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dai-re** [Awesomesh0t/awesomeshot#25]
![Screenshot_20220911-092008_Termux](https://user-images.githubusercontent.com/112737993/189509166-b1dd0786-7541-4d68-b772-738bf95a8cbd.jpg)

Nothing happen

**Comment by Dai-re** [comment]
![SmartSelect_20220911-101535_Termux](https://user-images.githubusercontent.com/112737993/189510917-c6da55e2-dfc5-4d75-a6a0-a97cdc1eb450.jpg)

![Screenshot_20220911-101628_Gallery](https://user-images.githubusercontent.com/112737993/189510922-5dabcca6-5cce-4466-a7a2-191af7401040.png)

**Comment by armandwipangestu** [comment]
v1.1.0 has a little bug, you can try the latest version it might solve your problem

## How to update awesomeshot?

### Termux

- Download or clone the latest release.

```bash
git clone -b termux https://github.com/Awesomesh0t/awesomeshot
```

- Run `make install` inside the script directory to install the script.

```bash
make install
```

### Linux

- Download or clone the latest release.

```bash
git clone -b linux https://github.com/Awesomesh0t/awesomeshot
```

- Run `make install` inside the script directory to install the script.

```bash
sudo make install
```

### NOTE

Don't forget to update new configuration file because there are different version, with command:

```bash
awesomeshot -c
```

![image](https://user-images.githubusercontent.com/64394320/189655121-066ad959-94b2-424e-8329-3bc33013f644.png)
